### ISSUE TITLE
Entity not set for addActionListener(phone)

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#10]
I am following tutorial and I am now at "Adding phone and video conferencing". In the code example from the tutorial we have:
``` java
addActionListener(phone, evt->{
    evt.consume();
    if (!CN.canDial()) {
        Dialog.show("Not supported", "Phone calls not supported on this device", "OK", null);
        return;
    }
    if (evt.getEntity().isEmpty(Person.telephone)) {
        Dialog.show("No Phone", "This user has no phone number", "OK", null);
        return;
    }

    String phoneNumber = evt.getEntity().getText(Person.telephone);
    CN.dial(phoneNumber);

});
```
However, the "evt.getEntity().getText(Person.telephone)" is always null. In fact all other properties like "evt.getEntity().getText(Thing.name)" is null as well.
It seems like the "evt" event does not have the property field filled at all.

**Comment by shannah** [comment]
Looks like there was a regression from some of the latest changes to CodeRAD that prevented event propagation in the AvatarProfileView title component.  You'll need to download the latest CodeRAD.cn1lib from [here](https://github.com/shannah/RADChatRoom/tree/master/bin).  This will fix it so that you can click on the "Title component" avatars.

That may not be directly related to your issue though.  If you are clicking on the avatar next to the individual chat bubbles, then the entity you receive with the event will depend on the model for your Chat messages.  If your view model has an "Entity" for the creator, then you'll receive that entity (the creator - so you'll be able to get the phone number if it has one).  If your view model for a chat message, instead just specifies the icon and participant name for the chat message as strings, then you'll receive the entity for the chat message - which probably won't have a phone number.

When you click on the "Title" component, you should see an action sheet as shown in the tutorial though... and the entity in the event will be the contact entity.

**Comment by arthef** [comment]
Thank you for your explanation. It appears that indeed the Entity under the bubble is for the chat message not the person. Hence the phone number is unavailable.
I tried to workaround this and add the 'creator/sender' of the message to the chat message as entity:
``` kotlin
    fun newMessage(content: String, sender: Contact, d: Date = Date()): Entity {
        val message = ChatBubbleView.ViewModel()
        message.messageText(content)
        message.postedBy(sender.getText(Thing.name))
        message.iconUrl(sender.getText(Thing.thumbnailUrl))      
        message.isOwn(sender.getBoolean(ChatMessage.isOwnMessage))
        message.date(d)

        message.setEntity(ChatMessage.author, sender) // <-- trying to add entity

        return message
    }
```
But still, in the event handler the event entity with chat message does not contain this additional 'author' entity. Is it possible that it is not copied over?

**Comment by shannah** [comment]
I have added a recipe that describes how to use an entity for the creator [here](https://shannah.github.io/RADChatRoom/cookbook/#_using_an_entity_for_the_posted_by_property_of_chat_message).

I just tested and it is passing through the correct entity for the avatar click events.

**Comment by arthef** [comment]
Thank you. I followed the updated tutorial and now it works correctly for me.
