### ISSUE TITLE
How to correctly define complex entity

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#9]
I would like to have a ChatMessage entity to have property sender. Sender is a 'Contact' entity with own definition:
``` kotlin
class Contact(n: String, a: String) : Entity() {
    var name: StringProperty?
    var avatar: StringProperty?
    private val TYPE: EntityType = object : EntityType() {
        init {
            name = string(tags(Thing.name))
            avatar = string(tags(Thing.thumbnailUrl))
        }
    }
    init {
        entityType = TYPE
        set(name, n)
        set(avatar, a)
    }
}
```
Now, I would like to have a ChatMessage entity defined like this:
``` kotlin
class ChatMessage(m: String, s: Contact) : Entity() {
    var sender: EntityProperty<Contact>
    var content: StringProperty?

    private val TYPE: EntityType = object : EntityType() {
        init {
            content = string(tags(ChatMessage.text))
            sender = entity(tags(ChatMessage.creator)) // <--- This is the place I do not understand 
         // how to specify the entity type
        }
    }

    init {
        entityType = TYPE
        set(content, m)
        set(sender, s)
    }
}
```
How to specify entity type of complex entities?

**Comment by shannah** [comment]
A couple of things here.  the TYPE variable should be static so that all instances of ChatMessage actually reference the same EntityType object.  Kotlin doesn't have static variables per-se.  I think the closest equivalent is a companion object.  So something like:

~~~~
class ChatMessage(m: String, s: Contact) : Entity() {
    companion object TYPE {
        init {
            string(tags(ChatMessage.text))
            entity(tags(ChatMessage.creator)) 
        }
    }

    init {
        entityType = TYPE
        set(ChatMessage.text, m)
        set(ChatMessage.creator, s)
    }
}
~~~~

Note.. I just changed it to loose coupling here for simplicity.  You don't really need to specify the entity type.  It makes things easier if you don't.  If you want to specify entity type, you could create a wrapper getter method that casts to your particular type of entity.  

NOTE:  I haven't really tried using Kotlin on CodeRAD yet.  In the java models, I've optimized for java syntax .  It may take a little playing around to find the nicest way to lay them out in Kotlin.

**Comment by arthef** [comment]
Thank you for suggestion but the compiler still does not accept this line:
``` kotlin
entity(tags(ChatMessage.creator))
```
It is asking me for a type: "Required: Class<TypeVariable(T)!>"
And this is the part I cannot get through, either in Java or Kotlin.
Java example is good enough for me too.

The "entity" method requires 2 parameters to it's call. I cannot find an example on how to pass the first argument.

**Comment by shannah** [comment]
Sorry.. I glossed over that part.   The entity() method requires you to pass the class of your entity as the first param.  Here is an example entity that has an entity property.

https://gist.github.com/shannah/83b4921a6418fe67a6a20cb91545c784

**Comment by arthef** [comment]
Thanks a lot, again. This solved the problem. For kotlin the actual syntax would be:
``` kotlin
entity(Contact::class.java, tags(ChatMessage.creator))
```

**Comment by shannah** [comment]
Good to know.  I'll need to look at a nicer syntax for Kotlin.  Class constants are ugly.

**Comment by arthef** [comment]
It is not that bad. The code is still compact and readable.
